# Generated by Django 5.2 on 2025-07-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentmodel',
            managers=[
            ],
        ),
    ]
