# Generated by Django 5.2 on 2025-07-13 17:56

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentmodel_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentmodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
