# Generated by Django 5.2 on 2025-07-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='visiblity',
            new_name='visibility',
        ),
    ]
